spring.application.name=R_erant_proyect
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/dbR_aurant
spring.datasource.username=postgres
spring.datasource.password=loco102938
server.port=8080